### PR TITLE
#589 Ignore null values inside props.children

### PR DESCRIPTION
**Pull request by tankh99**
- Added variable inside Carousel Component: filteredChildren; it filters out null values from props.children.
- Added the storybook: "Mixed Carousel" under the Advanced section which demonstrates that the carousel can allow both videos and images to exist within the same carousel

Let me know if there's anything more that needs to be added, this is my first pull request!

### CODE REVIEW

**Comment by tankh99** [comment]
Leaving a comment here in hopes someone will notice this

**Comment by leandrowd** [comment]
I believe the filtering should be done in the consumer side, the carousel explicitly requires only valid children to work. The maximum we should do inside the carousel is a validation and a console.error message I'd say.

**Comment by leandrowd** [comment]
Same reply as https://github.com/leandrowd/react-responsive-carousel/pull/579#issuecomment-872699378

**Comment by tankh99** [comment]
Currently, react-responsive-carousel doesn't support multimedia carousels, which is to say, videos and images in the same carousel. What this pull request aims to do is to introduce multimedia carousels, because as of now, the library will either show a black slide, or there it miscounts the number of slides due to it not ignoring null children

**Pull request closed without merging**
