### PR TITLE
Fix autoplay not re-starting after carousel has an update state

### PR DESCRIPTION
**Pull request by hiradyazdan**
This is a fix for issue https://github.com/leandrowd/react-responsive-carousel/issues/298#issuecomment-664627725

### CODE REVIEW

**Comment by hiradyazdan** [comment]
@leandrowd seriously? without any explanation why?

**Comment by leandrowd** [comment]
Another PR solving the same problem was merged yesterday,  sorry, forgot to update you.

**Comment by hiradyazdan** [comment]
would be nice if you could link that PR here as well so we know how the problem was solved.

**Comment by leandrowd** [comment]
Please check the recent merged Pre, feel free to reopen if you want, I'm
pretty busy with other stuff and have no idea when I'll be able to spend
time here tbh.

**Pull request closed without merging**
