### PR TITLE
Issue 266

### PR DESCRIPTION
**Pull request by guily19**
Fixed the accessibility error for the next and previous buttons

### CODE REVIEW

**Comment by leandrowd** [comment]
Great stuff @guily19 , thanks for the contribution! I have a few thoughts and would like your opinion.

1) Do you think we need labels for other controls too? If our goal is accessibility I would say yes. If the goal is just to pass a given validation, maybe. I would prefer to focus on the former.
2) Given that we might need more strings being passed down, I believe we could group all of them in a single object passed as a prop. (i.e: prop named labels with attributes like "leftArrow", "rightArrow", "controls", "item", etc)

Please let me know what you think.

**Comment by MattBridgeman** [comment]
@leandrowd @guily19 
1. I've been working with @guily19 on this and our use-case is passing accessibility tool validation but if you want more labels elsewhere we can look into that. If so could you list what you want labeled?
2. Makes sense we can work on that

**Comment by MattBridgeman** [comment]
@leandrowd @guily19 
Okay following you're comments I've done the following:
1. _Do you think we need labels for other controls too?_
  a. Labeled all previous and next buttons both in the carousel and thumb components
  b. labeled all slide item buttons in the carousel and thumb components
2. _I believe we could group all of them in a single object passed as a prop_
  a. I've created a `labels` object in props with a default value for "leftArrow", "rightArrow" and "item"

I've updated the readme too. Any other comments please let us know @leandrowd

**Comment by afnizarnur** [comment]
Any updates with this? waiting for this PR to be merged 😬

**Pull request merged**
